Repository fluxcd/flux, pull requests merged in 2018-10, with the labels that each got.

#1418 Update registry credentials FAQ
  site/faq.md
Labels: docs

#1426 Add names of maintainers to MAINTAINERS
  MAINTAINERS
Labels: FAQ, docs, enhancement

#1437 Describe how to override kubeconfig in docs
  deploy/flux-deployment.yaml
  site/faq.md
  site/troubleshooting.md
Labels: docs

#1441 Docs: added note about ignore annotation to fluxctl docs
  site/using.md
Labels: docs

#1445 Deal with case of no service request arguments
  http/daemon/server.go
Labels: bug, ☠ high user impact

#1452 Rename standalone docs
  README.md
  deploy/flux-deployment.yaml
  site/faq.md
  site/get-started.md
  site/installing.md
  site/standalone-setup.md
  site/troubleshooting.md
Labels: docs

#1459 Move controller Status* consts to cluster package
  cluster/cluster.go
  cluster/kubernetes/kubernetes.go
  cluster/kubernetes/resourcekinds.go
  remote/rpc/compat.go
Labels: refactor
