Repository fluxcd/flux, pull requests merged in 2018-12, with the labels that each got.

#1565 Reimplement Git timeout Helm operator
  chart/flux/templates/helm-operator-deployment.yaml
  cmd/helm-operator/main.go
  integrations/helm/chartsync/chartsync.go
  site/daemon.md
  site/helm-operator.md
Labels: helm

#1594 Document correct Helm op flags
  site/helm-operator.md
Labels: docs

#1553 Add CHANGELOG to Helm chart
  chart/flux/CHANGELOG.md
Labels: docs, helm

#1599 Use shasum -a 256 rather than sha256sum
  Makefile
Labels: build, dogfood
