Repository fluxcd/flux, pull requests merged in 2018-11, with the labels that each got.

#1484 TLS verification Helm operator
  Gopkg.lock
  Gopkg.toml
  chart/flux/templates/helm-operator-deployment.yaml
  chart/flux/templates/helm-tls.yaml
  chart/flux/values.yaml
  cmd/helm-operator/main.go
  integrations/helm/helm.go
  site/helm-operator.md
Labels: helm

#1474 making compiling work on raspberry pi's
  checkpoint/checkpoint_linux_amd64.go
  checkpoint/checkpoint_linux_arm.go
Labels: build

#1488 Minor updates to fluxctl docs
  site/faq.md
  site/fluxctl.md
  site/get-started.md
  site/standalone-setup.md
Labels: docs

#1490 Remove note about --bootstrapper=kubeadm.
  site/helm-get-started.md
Labels: docs

#1489 re-flow GKE note in get-started doc
  site/get-started.md
Labels: docs

#1492 Fix typos in helm-op docs
  site/helm-integration.md
Labels: docs

#1498 Fix typo in helm-get-started.md
  site/helm-get-started.md
Labels: docs

#1514 Update doc on release process
  internal_docs/releasing.md
Labels: docs

#1530 Prevent Helm release deletion of installed charts
  integrations/helm/release/release.go
Labels: ☠ high user impact

#1527 Use weaveworks/flux-get-started repo in docs
  chart/flux/README.md
  site/faq.md
  site/fluxctl.md
  site/get-started.md
  site/helm-get-started.md
  site/helm-integration.md
  site/helm-operator.md
Labels: docs

#1540 Use flux-get-started repository everywhere.
  chart/flux/values.yaml
  cmd/fluxd/main.go
  deploy/flux-deployment.yaml
  site/daemon.md
Labels: docs

#1547 add missing links between docs
  site/daemon.md
  site/standalone-setup.md
Labels: docs

#1549 List some popular integrations in main README.md
  README.md
Labels: docs

#1550 Fixed GitOps Istio example link
  README.md
Labels: docs

#1554 Fix icon URL Helm chart
  chart/flux/Chart.yaml
Labels: helm

#1548 Default to fluxctl use for getting git deploy key
  chart/flux/README.md
  chart/flux/templates/NOTES.txt
  site/get-started.md
  site/helm-get-started.md
Labels: docs

#1555 Add ToC to larger doc pages
  site/faq.md
  site/fluxctl.md
  site/get-started.md
  site/helm-get-started.md
  site/helm-integration.md
  site/standalone-setup.md
Labels: docs
