Repository fluxcd/flux, pull requests merged in 2019-07, with the labels that each got.

#2006 Provide optional rollback support for HelmReleases
  chart/flux/templates/helm-operator-crd.yaml
  cmd/helm-operator/main.go
  deploy-helm/flux-helm-release-crd.yaml
  integrations/apis/flux.weave.works/v1beta1/types.go
  integrations/apis/flux.weave.works/v1beta1/zz_generated.deepcopy.go
  integrations/helm/chartsync/chartsync.go
  integrations/helm/operator/operator.go
  integrations/helm/release/release.go
  integrations/helm/status/conditions.go
  integrations/helm/status/status.go
Labels: enhancement, helm

#2149 Support image formats with separate registry entry
  bin/kubeyaml
  cluster/kubernetes/resource/fluxhelmrelease.go
  cluster/kubernetes/resource/fluxhelmrelease_test.go
  docker/Dockerfile.flux
  site/helm-integration.md
Labels: helm

#2220 Document Helm operator rollback feature
  site/helm-integration.md
Labels: helm

#2235 Release Helm operator v0.10.0
  CHANGELOG-helmop.md
  chart/flux/values.yaml
  deploy-helm/helm-operator-deployment.yaml
  deploy-helm/weave-cloud-helm-operator-deployment.yaml
Labels: helm

#2238 Housekeeping: merge release/helm-0.10.x back into master
  CHANGELOG-helmop.md
  chart/flux/values.yaml
  deploy-helm/helm-operator-deployment.yaml
  deploy-helm/weave-cloud-helm-operator-deployment.yaml
Labels: helm

#2251 Fixed `rollback.timeout` type definition in CRD
  chart/flux/templates/helm-operator-crd.yaml
  deploy-helm/flux-helm-release-crd.yaml
Labels: helm

#2252 Use correct Helm repository domain in docs
  chart/flux/README.md
  site/annotations-tutorial.md
  site/helm-operator.md
Labels: docs

#2257 Update contact info in README
  CONTRIBUTING.md
  README.md
  site/upgrading-to-1.0.md
Labels: docs

#2273 Mock `getKubeConfigContextNamespace` in tests
  cmd/fluxctl/main_test.go
  cmd/fluxctl/release_cmd_test.go
Labels: build

#2279 Enhance Git proxy support
  docker/Dockerfile.flux
  docker/Dockerfile.helm-operator
  git/operations.go
Labels: enhancement

#2292 Fix values merge in helm-operator
  integrations/helm/release/release.go
  integrations/helm/release/release_test.go
Labels: helm

#2284 Rename `--registry-poll-interval`
  cmd/fluxd/main.go
  daemon/daemon.go
  daemon/images.go
  daemon/loop.go
  site/daemon.md
  site/faq.md
  test/flux-deploy-all.yaml
Labels: UX

#2283 Upgrade justinbarrick/go-k8s-portforward to d79fe1b9
  go.mod
  go.sum
Labels: enhancement

#2301 Build: kill all apt-get processes before package update
  .circleci/config.yml
Labels: build

#2302 Build: tweak killall to silence error
  .circleci/config.yml
Labels: build

#2152 Add read-the-docs support
  .circleci/config.yml
  .gitignore
  .readthedocs.yml
  CONTRIBUTING.md
  Makefile
  README.md
  chart/flux/Chart.yaml
  chart/flux/README.md
  chart/flux/templates/NOTES.txt
  daemon/errors.go
  deploy/flux-deployment.yaml
  docs/Dockerfile
  docs/Makefile
  docs/_static/custom.css
  docs/conf.py
  docs/development/building.md
  docs/development/get-started-developing.md
  docs/development/index.rst
  docs/faq.md
  docs/features/daemon.md
  docs/features/fluxyaml-config-files.md
  docs/features/garbagecollection.md
  docs/features/index.rst
  docs/helm/helm-integration.md
  docs/helm/helm-operator.md
  docs/helm/helm-upgrading-to-beta.md
  docs/helm/index.rst
  docs/how-it-works.md
  docs/images/deployment-pipeline.png
  docs/images/flux-cd-diagram.png
  docs/images/weave-flux.png
  docs/index.rst
  docs/install/get-started.md
  docs/install/helm-get-started.md
  docs/install/index.md
  docs/install/index.rst
  docs/install/standalone-setup.md
  docs/introduction.md
  docs/requirements.md
  docs/requirements.txt
  docs/troubleshooting.md
  docs/using/annotations-tutorial.md
  docs/using/fluxctl.md
  docs/using/git-gpg.md
  docs/using/index.rst
  docs/using/monitoring.md
  docs/using/upgrading-to-1.0.md
  git/errors.go
  install/generated_templates.gogen.go
  install/templates/flux-deployment.yaml.tmpl
  internal_docs/releasing.md
  release/errors.go
  remote/errors.go
Labels: docs

#2311 point to new mailing list
  CONTRIBUTING.md
  README.md
Labels: docs

#2313 Restructure and split Flux and Helm op docs
  CONTRIBUTING.md
  README.md
  chart/flux/Chart.yaml
  chart/flux/README.md
  chart/flux/templates/NOTES.txt
  deploy/flux-deployment.yaml
  docs/_files/deployment-pipeline.png
  docs/_files/flux-cd-diagram.png
  docs/_files/weave-flux.png
  docs/contributing/building.md
  docs/contributing/get-started-developing.md
  docs/contributing/index.rst
  docs/development/building.md
  docs/development/get-started-developing.md
  docs/development/index.rst
  docs/faq.md
  docs/features/index.rst
  docs/get-started/index.rst
  docs/guides/index.rst
  docs/guides/provide-own-ssh-key.md
  docs/guides/upgrading-to-1.0.md
  docs/guides/use-private-git-host.md
  docs/helm-operator/faq.md
  docs/helm-operator/guides/index.rst
  docs/helm-operator/guides/upgrading-to-beta.md
  docs/helm-operator/index.rst
  docs/helm-operator/references/helmrelease-custom-resource.md
  docs/helm-operator/references/index.rst
  docs/helm-operator/references/operator.md
  docs/helm-operator/troubleshooting.md
  docs/helm-operator/tutorials/get-started.md
  docs/helm-operator/tutorials/index.rst
  docs/helm/index.rst
  docs/index.rst
  docs/install/index.md
  docs/install/standalone-setup.md
  docs/references/blueprint.md
  docs/references/daemon.md
  docs/references/fluxctl.md
  docs/references/fluxyaml-config-files.md
  docs/references/garbagecollection.md
  docs/references/git-gpg.md
  docs/references/helm-operator-integration.md
  docs/references/index.rst
  docs/references/monitoring.md
  docs/troubleshooting.md
  docs/tutorials/driving-flux.md
  docs/tutorials/get-started-helm.md
  docs/tutorials/get-started.md
  docs/tutorials/index.rst
  docs/using/index.rst
  git/errors.go
  install/generated_templates.gogen.go
  install/templates/flux-deployment.yaml.tmpl
  internal_docs/releasing.md
  remote/errors.go
Labels: docs

#2314 Fix broken link in `README.md`
  README.md
Labels: docs

#2315 Link to docs website instead of Markdown files
  README.md
Labels: docs

#2317 Typo: 'HelmUpradeFailed' -> 'HelmUpgradeFailed'
  integrations/helm/chartsync/chartsync.go
Labels: helm
