Repository fluxcd/flux, pull requests merged in 2019-04, with the labels that each got.

#1865 Detect changes made to git source in HelmRelease
  integrations/helm/chartsync/chartsync.go
Labels: helm

#1910 Reimplement `--git-poll-interval` in Helm operator
  chart/flux/README.md
  chart/flux/templates/helm-operator-deployment.yaml
  cmd/helm-operator/main.go
  integrations/helm/chartsync/chartsync.go
  site/helm-operator.md
  test/e2e/e2e-flux-chart.sh
Labels: helm

#1863 Less scary AWS detection
  chart/flux/README.md
  chart/flux/templates/deployment.yaml
  chart/flux/values.yaml
  cmd/fluxd/main.go
  registry/aws.go
  site/daemon.md
Labels: UX, dogfood

#1909 Support loading values from alternative files in chart
  chart/flux/templates/helm-operator-crd.yaml
  deploy-helm/flux-helm-release-crd.yaml
  integrations/apis/flux.weave.works/v1beta1/types.go
  integrations/apis/flux.weave.works/v1beta1/zz_generated.deepcopy.go
  integrations/helm/release/release.go
  site/helm-integration.md
Labels: helm

#1912 Fix instructions for observing colour change
  site/get-started.md
Labels: docs

#1920 Release Helm operator v0.8.0
  CHANGELOG-helmop.md
  deploy-helm/helm-operator-deployment.yaml
  deploy-helm/weave-cloud-helm-operator-deployment.yaml
Labels: helm

#1923 Housekeeping: merge release/helm-0.8.x back into master
  CHANGELOG-helmop.md
  deploy-helm/helm-operator-deployment.yaml
  deploy-helm/weave-cloud-helm-operator-deployment.yaml
Labels: helm

#1906 Make all Helm releases through the operator
  chart/flux/templates/helm-operator-crd.yaml
  cmd/helm-operator/main.go
  deploy-helm/flux-helm-release-crd.yaml
  integrations/apis/flux.weave.works/v1beta1/types.go
  integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/fake/fake_helmrelease.go
  integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/helmrelease.go
  integrations/helm/chartsync/chartsync.go
  integrations/helm/helm.go
  integrations/helm/http/daemon/server.go
  integrations/helm/operator/operator.go
  integrations/helm/status/conditions.go
  integrations/helm/status/status.go
Labels: helm

#1949 Move images to Docker Hub
  .circleci/config.yml
  Makefile
  api/v9/change_test.go
  chart/flux/README.md
  chart/flux/values.yaml
  deploy-helm/helm-operator-deployment.yaml
  deploy-helm/weave-cloud-helm-operator-deployment.yaml
  deploy/flux-deployment.yaml
  image/image.go
  internal_docs/releasing.md
  registry/cache/memcached/integration_test.go
  registry/cache/registry.go
  registry/client.go
  registry/imageentry_test.go
  site/faq.md
  site/get-started-developing.md
  site/troubleshooting.md
  test/bin/test-flux
  test/e2e/e2e-flux-chart.sh
  test/flux-deploy-all.yaml
Labels: build

#1956 Give master builds their own prerelease homes
  .circleci/config.yml
  site/faq.md
Labels: build

#1996 Typo: 'workspace' -> 'workload'
  cmd/fluxctl/automate_cmd.go
  cmd/fluxctl/deautomate_cmd.go
  cmd/fluxctl/list_images_cmd.go
  cmd/fluxctl/lock_cmd.go
  cmd/fluxctl/policy_cmd.go
Labels: UX

#1995 Update MAINTAINERS and include email addresses
  MAINTAINERS
Labels: docs

#1998 Add helm release reinstall procedure to docs
  site/helm-integration.md
Labels: docs
