Repository fluxcd/flux, pull requests merged in 2020-03, with the labels that each got.

#2887 Updated helm operator CRD URL in the documentation
  docs/tutorials/get-started-helm.md
Labels: docs

#2847 Support setting `priorityClassName` for memcached
  chart/flux/README.md
  chart/flux/templates/memcached.yaml
  chart/flux/values.yaml
Labels: helm-chart

#2898 Add MediaMarktSaturn to list of production users
  README.md
Labels: docs

#2879 Add memcached resource requests
  chart/flux/values.yaml
Labels: helm-chart

#2912 [docs] mention new fluxctl arch linux package
  docs/references/fluxctl.md
Labels: docs

#2915 Publish fluxctl to Docker Hub
  .circleci/config.yml
  Makefile
  docker/Dockerfile.fluxctl
Labels: build

#2930 Add Chattigo to list of production users
  README.md
Labels: docs

#2922 address CVE-2020-6750 for glib
  docker/Dockerfile.flux
Labels: build

#2919 move to mkdocs
  .circleci/config.yml
  .github/workflows/check-links.yaml
  .gitignore
  .readthedocs.yml
  Makefile
  README.md
  chart/flux/CHANGELOG.md
  chart/flux/templates/NOTES.txt
  deploy/flux-deployment.yaml
  docs/Dockerfile
  docs/Makefile
  docs/_static/custom.css
  docs/conf.py
  docs/contributing/index.rst
  docs/get-started/index.md
  docs/get-started/index.rst
  docs/guides/index.rst
  docs/index.md
  docs/index.rst
  docs/references/fluxctl.md
  docs/references/index.rst
  docs/requirements.txt
  docs/tutorials/index.rst
  mkdocs.yml
  pkg/daemon/errors.go
  pkg/git/errors.go
  pkg/install/templates/flux-deployment.yaml.tmpl
  pkg/release/errors.go
Labels: docs

#2942 build: regenerate generated_templates.gogen.go
  Makefile
  pkg/install/generated_templates.gogen.go
Labels: build

#2941 docs: nitpicks
  docs/index.md
  docs/references/automated-image-update.md
  docs/references/helm-operator-integration.md
  docs/tutorials/get-started-helm.md
  internal/docs/releasing.md
  mkdocs.yml
Labels: docs

#2943 Add Okteto Cloud as a production user
  README.md
Labels: docs

#2940 ci: Migrate tests to GitHub actions
  .circleci/config.yml
  .github/workflows/ci-cleanup.yaml
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  Makefile
  test/e2e/fixtures/kustom/base/gitsrv/gitsrv.yaml
  test/e2e/run-gh.bash
Labels: build
