Repository fluxcd/flux, pull requests merged in 2020-10, with the labels that each got.

#3144 Specific documentation for HelmRelease Automation
  docs/references/helm-operator-integration.md
Labels: docs

#3311 Fixup configmap in Git GPG documentation
  docs/references/git-gpg.md
Labels: size/small

#3280 Add PicsArt to Flux users
  README.md
Labels: size/small

#3315 Adds Wildlife Studios to the production users list
  README.md
Labels: size/small

#3290 Add Belvo as Flux user
  README.md
Labels: size/small

#3333 Add maintenance notice to help section
  README.md
Labels: docs

#3335 Update next GitOps Days Community Ed in help section
  README.md
Labels: docs

#3109 Add value 'extraEnvsFrom' to Helm Chart
  chart/flux/README.md
  chart/flux/templates/deployment.yaml
  chart/flux/values.yaml
Labels: helm-chart

#3345 snap: update build to use go 1.15
  snap/snapcraft.yaml
Labels: build
