Repository fluxcd/flux, pull requests merged in 2020-05, with the labels that each got.

#3023 Add guide to use GKE workload identity with private GCR registry
  docs/guides/use-gke-workload-identity.md
  mkdocs.yml
Labels: docs

#3047 Update docs for changing default namespace
  docs/faq.md
  docs/requirements.md
Labels: docs

#3016 Whitelist 3 env vars for Git cmd executions
  pkg/git/operations.go
Labels: enhancement

#2995 Adding Resulta to company list
  README.md
Labels: docs

#2993 Adding Greenpass to company list
  README.md
Labels: docs

#3008 Take all resource versions into account during GC
  pkg/cluster/kubernetes/sync.go
Labels: bug

#3053 Support annotations in chart SSH secret
  chart/flux/README.md
  chart/flux/templates/secret.yaml
  chart/flux/values.yaml
Labels: helm-chart

#3060 docs: update helm operator integration glob patterns
  docs/references/helm-operator-integration.md
Labels: docs

#3067 Updated "Alea Play Solutions" URL in "Who is using Flux in production"
  README.md
Labels: docs

#3072 build fluxctl snap using GH action
  .github/workflows/docs.yaml
  .github/workflows/fluxctl-snap.yaml
  docs/faq.md
Labels: build

#3084 Fix markup in ordered lists + fenced code groups
  docs/tutorials/get-started-helm.md
  mkdocs.yml
Labels: docs

#3086 ci: Run CVE scanning for latest release and master build
  .github/workflows/cve-scan.yaml
Labels: build

#3085 Migrate chart publishing to GitHub Actions
  .circleci/config.yml
  .github/workflows/chart-release.yml
Labels: build
