Repository fluxcd/flux, pull requests merged in 2020-07, with the labels that each got.

#3175 Disable Snapcraft job
  .github/workflows/cve-scan.yaml
  .github/workflows/fluxctl-snap.yaml
Labels: build

#3176 Update kubectl and kustomize
  docker/kubectl.version
  docker/kustomize.version
Labels: build

#2986 Introduce cooldown period in rate limiter
  pkg/registry/middleware/rate_limiter.go
Labels: enhancement

#3181 Release Helm chart v1.4.0
  chart/flux/CHANGELOG.md
  chart/flux/Chart.yaml
Labels: helm-chart

#3204 Give advice on percent-encoding creds using in URL
  docs/guides/use-git-https.md
Labels: docs

#3211 Dockerfile: Include /sbin dir in PATH
  docker/Dockerfile.flux
Labels: build

#3208 chart: add kube.externalConfig option
  chart/flux/README.md
  chart/flux/templates/deployment.yaml
  chart/flux/templates/kube.yaml
  chart/flux/values.yaml
Labels: helm-chart
